export interface Product {
    id: number;
    link: string;
    name: string;
    img: string[];
    price: number;
    description: string;
    rating: number;
    currentImageIndex: number;
    categoryId: number;
    likes: number;
}

export const products = [
    {
        id: 1,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/hc7/h59/67189057028126.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h8a/h46/67189057552414.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h8c/hb1/85996739199006.png?format=gallery-medium"],
        name: 'Fourdoor wardrobe with mirror, 160x200x47 cm, white',
        price: 77800,
        description: 'Fourdoor Swing Wardrobe with Mirror, 160x200x47 cm, White',
        link: 'https://kaspi.kz/shop/p/raspashnoi-shkaf-fourdoor-s-zerkalom-160x200h47-sm-belyi-108174703/?c=750000000',
        rating: 4,
        currentImageIndex: 0,
        categoryId: 4,
        likes: 145,
    },
    {
        id: 2,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/hf4/h52/64509322919966.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h86/h70/64509325803550.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h45/hb7/64509328457758.jpg?format=gallery-medium"],
        name: 'Apple MacBook Air 13 2022 13.6’ / 8GB / 256GB SSD / macOS / MLXW3',
        price: 490693,
        description: 'The MacBook Air 2022 has undergone significant updates, including a complete redesign and the introduction of a more powerful M2 processor. The M2 processor offers improved graphics performance, surpassing both the M1 and Intel-powered MacBook models. The overall computing power gains are 18%, with the M2 outperforming the M1 by a factor of 1.5 in many tasks and showing an impressive 300% difference when encoding ProRes video. The MacBook Air also features a comfortable backlit keyboard with large function keys, a large Force Touch-enabled trackpad, and an upgraded Full HD webcam. Additionally, the laptop is equipped with a MagSafe 3 connector for easy charging. The sound system has been enhanced with quadrophonic surround sound speakers, Spatial Audio, and Dolby Atmos. Overall, the MacBook Air 2022 offers improved performance, comfort, and multimedia experience.',
        link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2022-13-6-8-gb-ssd-256-gb-macos-mlxw3-105933794/?c=750000000',
        rating: 5,
        currentImageIndex: 0,
        categoryId: 2,
        likes: 124,
    },
    {
        id: 3,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/hd7/h74/63950404878366.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h12/h5a/63950406582302.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/hb9/h89/63950413692958.jpg?format=gallery-medium"],
        name: 'Hoover Deerma DX700S grey ',
        price: 14998,
        description: 'The Deerma DX700S upright vacuum has cyclonic technology with a powerful motor for dry cleaning. It is also hand-held, with a 0.8 litre transparent plastic dirt container.',
        link: 'https://kaspi.kz/shop/p/smart-32g7000-81-sm-chernyi-109729462/?c=750000000',
        rating: 5,
        currentImageIndex: 0,
        categoryId: 4,
        likes: 715,
    },
    {
        id: 4,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h90/hd8/85539374170142.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h8f/h98/85539374235678.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h61/h0c/85539374301214.jpg?format=gallery-medium"],
        name: 'AVA Microwave Oven MMWO-2070B Black',
        price: 24990,
        description: 'GrillNo ConvectionNo Microwave power700.0 W Number of power levels5 Control panel Control typemechanical Rotary type of control DisplayNo Timer35.0 min Other Hinged door Other functions and features audible alarm General characteristics Internal volume20.0 litres Freestanding Width46.6 cm Height33.6 cm Depth24.3 cm Tray diameter255.0 mm Without turntableNo Enamel interior coating',
        link: 'https://kaspi.kz/shop/p/ava-mmwo-2070b-chernyi-117793364/?c=750000000',
        rating: 5,
        currentImageIndex: 0,
        categoryId: 4,
        likes: 240,
    }, {
        id: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h9e/ha3/86233669632030.jpg?format=gallery-medium"],
        name: 'BestGamer 064 system unit',
        price: 419700,
        description: ' BestGamer 069 gaming computer based on Intel Core I5 12400f processor and RTX 4060 graphics card, which will cope with any competitive games! Video card: NVIDIA GeForce RTX 4060. Processor: Intel Core I5 12400f. Motherboard: H610 with the possibility of modification. RAM: 2x16 GB 3200mhz with the possibility of adding. SSD drive: 1000 GB with the possibility of adding',
        link: 'https://kaspi.kz/shop/p/bestgamer-064-i5-12400f-rtx-4060-32gb-ssd-1000-gb-win-11-pro-120175484/?c=750000000',
        rating: 5,
        currentImageIndex: 0,
        categoryId: 2,
        likes: 43,
    }, {
        id: 6,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h47/ha1/64094073815070.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/hcf/ha8/64094074798110.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h5a/h8f/64094077124638.jpg?format=gallery-medium"],
        name: "Generic SF-400 Kitchen Scale",
        price: 799,
        description: "This modern electronic kitchen scale has an elegant platform made of plastic. The scales are made in a white casing. The weighing limit is 10kg",
        link: "https://kaspi.kz/shop/p/generic-sf-400-102531445/?c=750000000",
        rating: 5,
        currentImageIndex: 0,
        categoryId: 4,
        likes: 1401,
    }, {
        id: 7,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h03/h02/64026264174622.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/hb3/hfa/64026265518110.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h9f/h05/64026268467230.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h0e/h71/64026270498846.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h2e/hda/64026273939486.jpg?format=gallery-medium"],
        name: "Samsung Odyssey G9 C49G95TSSI LC49G95TSSIXCI",
        price: 958898,
        description: "Diagonal: 48.9 inches, Resolution: 5120x1440, LCD Matrix Type: TFT *VA, Brightness: 420.0 cd/m², Response Time: 1.0 ms, Max Refresh Rate: 240.0 Hz, Inputs: HDMI, DisplayPort.",
        link: "https://kaspi.kz/shop/p/samsung-odyssey-g9-c49g95tssi-lc49g95tssixci-chernyi-belyi-101114775/?c=750000000",
        rating: 4.5,
        currentImageIndex: 0,
        categoryId: 4,
        likes: 1094,
    }
    , {
        id: 8,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h32/h70/84378448199710.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h3d/h8e/64208874405918.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/hfe/h17/64208876634142.jpg?format=gallery-medium"],
        name: "Apple iPhone 13 128Gb Smartphone Black",
        price: 269571,
        description: "4G (LTE) Yes Standard GSM 850/900/1800/1900, 3G, 4G LTE, 5G Operating system iOS 15 SIM card nano SIM + eSIM Material metal and glass 5G support Yes NFC technology Yes Colour black.",
        link: "https://kaspi.kz/shop/p/apple-iphone-13-128gb-chernyi-102298404/?c=750000000",
        rating: 5,
        currentImageIndex: 0,
        categoryId: 1,
        likes: 160,
    }, {
        id: 9,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/hf5/hf5/84077662830622.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/hfe/hbf/84077662961694.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h11/h43/84077663027230.jpg?format=gallery-medium"],
        name: "Dyson Gen5detect",
        price: 576482,
        description: "Type: Vertical, Cleaning: Dry, Dust Collector Type: Container, Power Consumption: 752.0 W, Power Source: Battery, Color: Purple.",
        link: "https://kaspi.kz/shop/p/dyson-gen5detect-fioletovyi-113592857/?c=750000000",
        rating: 4.5,
        currentImageIndex: 0,
        categoryId: 4,
        likes: 140,
    },
    {
        id: 10,
        name: 'ThundeRobot laptop',
        price: 388977,
        description: 'ThundeRobot 911S Core D 15.6’ / 16GB / 512GB SSD / No OS / JT009K00F',
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h76/h6c/85301691547678.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/ha4/hf8/85301691613214.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h91/h27/85301691678750.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/thunderobot-911s-core-d-15-6-16-gb-ssd-512-gb-bez-os-jt009k00f-117046774/?c=750000000",
        categoryId: 2,
        currentImageIndex: 0,
        likes: 106,
    },
    {
        id: 11,
        name: 'GIGABYTE Notebook',
        price: 649966,
        description: 'GIGABYTE G6X 9KG 16’ / 16GB / 1000GB SSD / DOS / 9KG-43KZ854SD',
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/pee/p4c/27566343.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p00/p51/27566359.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/pdd/p53/27566364.png?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/gigabyte-g6x-9kg-16-16-gb-ssd-1000-gb-dos-9kg-43kz854sd-117005217/?c=750000000",
        categoryId: 2,
        likes: 18,
        currentImageIndex: 0,
    },
    {
        id: 12,
        name: 'BestGamer 022 i7-12700F/ RTX 4060/ 32GB/ 1000GB HDD+SSD 512GB/ Win 11 Pro system unit',
        price: 619000,
        description: "This PC is more than just a tool - it's your portal to a world of power and efficiency. Whether you're gaming, creating or working, this kit is ready to turn your ambitions into reality. Make your choice today and go to new heights! Your computer is assembled, configured, optimised and ready to go!",
        rating: 4,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/p37/p0a/14221722.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p1a/p0a/14221723.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/bestgamer-022-i7-12700f-rtx-4060-32gb-1000-gb-hdd-ssd-512-gb-win-11-pro-121725692/?c=750000000",
        categoryId: 2,
        currentImageIndex: 0,
        likes: 32,
    },
    {
        id: 13,
        name: 'Apple iPhone 14 Pro 256Gb Black',
        price: 549690,
        description: 'The iPhone 14 Pro is a groundbreaking smartphone with a range of impressive features. It emphasizes status and aims to satisfy demanding users. The model offers a durable ceramic screen and IP68 water and dust protection, making it reliable and worry-free. The 6.1" Super Retina XDR OLED display with adaptive refresh rate technology provides a vibrant and energy-efficient viewing experience. Powered by the A16 bionic chip, the iPhone 14 Pro boasts top-notch performance, with the ability to handle the most demanding tasks. The innovative Dynamic Island feature keeps users up to date with important events and offers quick access to essential features. The smartphone prioritizes security with SMS communication with emergency services, as well as automatic contact with emergency services and loved ones in the event of a car accident. The iPhone 14 Pro also showcases a brand-new camera system, including a 48 MP main camera and various modes and effects for professional-quality photos. With a long battery life and support for MagSafe fast wireless charging, the iPhone 14 Pro is a comprehensive and advanced smartphone option.',
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h19/h85/64508108931102.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/ha5/hae/64508111912990.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h11/h2e/64508113485854.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/he8/h62/64508118794270.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h02/h9b/64508121710622.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/apple-iphone-14-pro-256gb-chernyi-106363265/?c=750000000",
        categoryId: 1,
        currentImageIndex: 0,
        likes: 11,
    },
    {
        id: 14,
        name: ' Google Pixel 7 8 Gb/128Gb White',
        price: 542111,
        description: '4G (LTE)Yes StandardGSM 850/900/1800/1900, 3G, 4G LTE, 5G Operating systemAndroid 14 SIM cardPapo SIM + eSIM MaterialTitanium and glass 5G supportYes NFC technologyYes Colour Black',
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/hd1/h74/84963524706334.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/haa/h49/84963524771870.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h28/h8f/84963582607390.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/samsung-galaxy-s24-ultra-5g-12-gb-512-gb-chernyi-116044201/?c=750000000",
        categoryId: 1,
        likes: 217,
        currentImageIndex: 0,
    }, {
        id: 15,
        name: ' Samsung Galaxy S25 Ultra 5G 12GB/256GB Smartphone Dark Black',
        price: 613783,
        description: '4G (LTE)Yes Standard5G Operating systemAndroid SIM cardPapa SIM+eSIM MaterialMetal and glass 5G supportYes NFC technologyYes Colour Black',
        rating: 4,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/pa8/pcf/20117665.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/pc4/pcf/20117666.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/pe0/pcf/20117667.png?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/samsung-galaxy-s25-ultra-5g-12-gb-256-gb-temno-chernyi-133434571/?c=750000000",
        categoryId: 1,
        likes: 20,
        currentImageIndex: 0,
    }, {
        id: 16,
        name: "Apple iPhone 16 Pro 128Gb Black",
        price: 567673,
        description: "4G (LTE)Yes StandardGSM 850/900/1800/1900, 3G, 4G LTE, 5G Operating systemiOS 18 SIM cardPapo SIM + eSIM MaterialMetal and glass 5G supportYes NFC technologyYes Colour Black",
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h8d/h0d/87295483052062.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h9b/h6a/87295483084830.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h52/h81/87295483117598.png?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/apple-iphone-16-pro-128gb-chernyi-123787019/?c=750000000",
        categoryId: 1,
        likes: 180,
        currentImageIndex: 0,
    },
    {
        id: 17,
        name: "Apple Watch Series 10 S/M 42mm Gold-White smartwatch",
        price: 213911,
        description: "The Apple Watch Series 10 has been updated with new and exciting features that make it a desirable choice. It now boasts a larger, more vibrant display and a slim, sleek, and durable case that is 10% thinner and lighter than the previous model. The Series 10 is equipped with a depth sensor that automatically detects water depths up to 6 metres, making it useful for swimmers or divers. Additionally, it has a sleep sensor with an apnoea warning, which can alert users to potential sleep and health issues. The watch also features an improved speaker, allowing users to listen to podcasts or music without their phone, although this feature is better suited for home use. The battery life remains at 18 hours, but fast charging now allows the watch to reach 80% charge in just 30 minutes. Overall, the Apple Watch Series 10 is a reliable workout partner, personal assistant, and stylish daily accessory",
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/p45/p26/3345922.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p44/paa/3346092.png?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p28/paa/3346093.png?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/apple-watch-series-10-s-m-42-mm-zolotistyi-belyi-128574070/?c=750000000",
        categoryId: 3,
        likes: 62,
        currentImageIndex: 0,
    },
    {
        id: 18,
        name: 'Garmin Forerunner 965 smartwatch black',
        price: 327789,
        description: "The Garmin Forerunner 965 is a durable sports watch that offers features to track various physical activities and monitor heart rate and sleep quality. Made of plastic and titanium, it ensures strength and durability. The 1.4-inch touchscreen is designed to be easily viewable even in bright sunlight. The watch is equipped with sensors and features to track a range of physical activities, including running, walking, swimming, cycling, yoga, and Pilates. With its built-in GPS receiver, it can record workout routes, speed, distance, and pace, providing valuable insights into the user's fitness. Additionally, the watch features PulseOx technology, which measures blood oxygen saturation levels. Overall, the Garmin Forerunner 965 is a versatile sports watch that offers comprehensive tracking capabilities for various exercises and provides important health data such as heart rate and sleep quality.",
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/hdc/hce/86182020055070.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h65/hd6/86182020087838.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h66/h6d/86182020120606.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/garmin-forerunner-965-chernyi-109351643/?c=750000000",
        categoryId: 3,
        likes: 106,
        currentImageIndex: 0,
    },
    {
        id: 19,
        name: 'Samsung Galaxy Watch Ultra 47mm silver-black smartwatch',
        price: 224997,
        description: "Introducing the Galaxy Watch Ultra, a revolutionary health care device powered by AI. With the ability to withstand extreme conditions, such as heat up to 55°C and 9000m altitude, this watch is designed for those seeking new challenges. The watch is equipped with a powerful 3nm processor and a long-lasting battery that can go up to 100 hours in power saving mode. The BioActive sensor collects accurate data, which is then analysed by Galaxy AI to help users achieve their goals. In addition, the watch features a Quick Action Button that can activate a powerful siren in case of emergencies, an SOS signal for falls, and immediate access to medical information. For those venturing into the night, the watch automatically switches to night mode, preserving night vision. The Galaxy Watch Ultra is the perfect companion for those looking to push their limits.",
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/h03/h68/86681927876638.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h23/hc4/86681927942174.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/h4b/h93/86681928007710.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/samsung-galaxy-watch-ultra-47-mm-serebristyi-chernyi-122020632/?c=750000000",
        categoryId: 3,
        likes: 34,
        currentImageIndex: 0,
    },
    {
        id: 20,
        name: 'Apple Watch Series 10 S/M 42mm Silver-Blue smartwatch',
        price: 214848,
        description: "The Apple Watch Series 10 brings a host of new features and improvements that make it a compelling choice for users. It boasts a larger screen and a slimmer, more durable case, offering a sleek and stylish design. The watch now includes a depth sensor, allowing users to automatically detect water depths up to 6 meters, making it ideal for swimming or diving. A sleep sensor with apnea warning has been added, providing alerts for potential sleep and health issues. The updated speaker enables users to listen to podcasts and music without their phone directly from the watch. The Series 10 is 10% thinner and lighter than its predecessor, making it more comfortable for daily wear and sleep tracking. The display is the largest in Apple Watch history, with increased brightness and enhanced angular visibility. The battery life remains at 18 hours, but fast charging has been introduced, enabling an 80% charge in just 30 minutes. Overall, the Apple Watch Series 10 is a reliable and stylish companion for everyday use.",
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/p06/p00/2456246.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/pe3/p02/2456251.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p38/p03/2456254.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/apple-watch-series-10-s-m-42-mm-serebristyi-sinii-128355394/?c=750000000",
        categoryId: 3,
        likes: 11,
        currentImageIndex: 0,
    }, {
        id: 21,
        name: 'Garmin VENU 3S Gold Beige Smartwatch',
        price: 239212,
        description: "Introducing the Garmin Venu 3 smartwatch, a powerful wrist-based trainer designed to help you achieve your fitness and health goals. With a long battery life of up to 14 days, this smart GPS watch is packed with advanced features to track and understand your body better. Engage in a variety of activities with animated workouts and access over 30 built-in sports apps, including specific options for active wheelchair users. Take advantage of advanced workout features to improve your strength and overall fitness. The Venu 3 also enables seamless communication with a built-in speaker and microphone, allowing you to make and receive calls directly from your wrist when connected to your smartphone. You can even use your phone's voice assistant to respond to text messages. Stay connected with additional features like music storage and Garmin Pay for contactless payments.",
        rating: 5,
        img: ["https://resources.cdn-kaspi.kz/img/m/p/pa8/p2e/26684850.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p53/p2e/26684853.jpg?format=gallery-medium", "https://resources.cdn-kaspi.kz/img/m/p/p37/p2e/26684854.jpg?format=gallery-medium"],
        link: "https://kaspi.kz/shop/p/garmin-venu-3s-zolotistyi-bezhevyi-113029870/?c=750000000",
        categoryId: 3,
        likes: 29,
        currentImageIndex: 0,
    },
];

